### PR TITLE
MINOR: [Release] Update versions for 15.0.2

### PR DESCRIPTION
**Pull request by amoeba**

### CODE REVIEW

**Comment by raulcd** [comment]
I am not entirely sure why the Java test for flight is failing with:
```
Exception java.lang.NoClassDefFoundError: io/grpc/BindableService
      at FlightServer.builder (FlightServer.java:169)
      at (#39:4)
Caused by: java.lang.ClassNotFoundException: io.grpc.BindableService
      at BuiltinClassLoader.loadClass (BuiltinClassLoader.java:641)
      at ClassLoaders$AppClassLoader.loadClass (ClassLoaders.java:188)
      at ClassLoader.loadClass (ClassLoader.java:521)
```

**Comment by amoeba** [comment]
I'll look into it later today and report back.

**Comment by amoeba** [comment]
I wasn't able to reproduce the error locally, though I do get a failure in the avro cookbook:

```
Expected:
    name    favorite_number    favorite_color
    Alyssa    256    null
    Ben    7    red
Got:

```

(no output)

I'm going to re-run the failed jobs to see if it's just a transient issue and then see about the Avro issue.

**Comment by amoeba** [comment]
Hey @raulcd, I forgot about this but took another look today. I re-ran this patch locally and it works fine now? I'm not sure what might have changed.

I am able to reproduce the above grpc error on 16.0.0-SNAPSHOT so I can look into that elsewhere. Otherwise, I think this is ready for a merge.

**Review by raulcd — APPROVED** [review]
LGTM and CI is passing now.

**Pull request merged**
