### PR TITLE
[Java] Add splicing non-zero index example

### PR DESCRIPTION
**Pull request by mystic-lama**
Added example for splicing from a non-zero index

### CODE REVIEW

**Comment by mystic-lama** [comment]
@lidavidm added non-zero index example

Probably last PR for this week :) If you have any more idea's for to be included in cookbook, send my way

**Comment by lidavidm** [comment]
Thank you!

I don't think this is different enough to warrant a separate example though; when I asked, I was just thinking we could modify the parameters in the original example

**Comment by mystic-lama** [comment]
Got it. May be we can close this PR or do you want me to update the original example with different params?

**Comment by lidavidm** [comment]
I would say, just add another block like this to the original example:

```java
       tp = vector.getTransferPair(allocator);
       tp.splitAndTransfer(2, 6);
       try (IntVector sliced = (IntVector) tp.getTo()) {
           System.out.print(sliced);
       }
```

**Review by lidavidm — APPROVED** [review]

**Pull request merged**
