### PR TITLE
[R] Remove no-longer-true content on calling functions

### PR DESCRIPTION
**Pull request by thisisnic**
This PR removes information which is incorrect as of v 9.0.0 of Arrow

### CODE REVIEW

**Comment by mystic-lama** [comment]
+1 LGTM

**Comment by mystic-lama** [comment]
@lidavidm Please look at this PR when you get time

**Comment by lidavidm** [comment]
I trust Nic with the PR; I'm not familiar enough with R to review

**Comment by thisisnic** [comment]
Merging it now so it unblocks others' work.

**Pull request merged**
