### PR TITLE
Add Apache publishing / hosting

### PR DESCRIPTION
**Pull request by westonpace**
Very similar to #28 but adds the subdir.

### CODE REVIEW

**Comment by westonpace** [comment]
Leaving in draft to wait for feedback from ML

**Comment by thisisnic** [comment]
Just wondering - do you think there anything else we would need to do to make this change publish to arrow.apache.org/cookbook instead of arrow-cookbook.apache.org/cookbook?

**Comment by westonpace** [comment]
I don't think so but I agree the docs are vague.  I see your interpretation in #28 ...

> By default, web sites will be published at $project.apache.org where $project is the sub-domain name of your project, as determined by the repository name.

The "as determined by the repository name" and "$project is the sub-domain" certainly makes it seem like it would be arrow-cookbook.

However, `arrow-site` publishes to `arrow` so that is confusing.  I could believe that maybe the repo name is used to lookup the project name and the project name is used for publishing.

I could also believe that `arrow-site` has some legacy configuration settings from pre-`.asf.yaml` days and your interpretation is indeed correct.

So my hope is to start with this PR, see what happens, and if it is wrong, iterate from there.

**Comment by westonpace** [comment]
Ah, when in doubt, refer to the source :)

https://github.com/apache/infrastructure-puppet/blob/e3dbb3c947dd1191b91ccd99e0f690802bff5b4c/modules/gitbox/files/asfgit/asfyaml.py#L591

The regex `re.match(r"(?:incubator-)?([^-.]+)", cfg.repo_name)` strips off any leading `incubator-` and then grabs everything up to the first `-`.  So `arrow-cookbook` will resolve to `arrow`.

**Comment by thisisnic** [comment]
Wow, nice find! Never would have guessed that from the docs! 😬

**Comment by westonpace** [comment]
No activity on the ML.  I'm going to try enabling this over the weekend so hopefully the impact is minimal if anything breaks.

**Comment by westonpace** [comment]
Well, it doesn't seem that anything broke but the site also isn't hosted.  I'll follow up with Infra tomorrow.

**Pull request merged**
