### PR TITLE
Use ARROW_RETURN_NOT_OK (and friends) instead of ASSERT_OK (and friends) in recipes

### PR DESCRIPTION
**Pull request by westonpace**
Addresses #44

### CODE REVIEW

**Comment by pitrou** [comment]
Can you update cpp/CONTRIBUTING.md for the recipe API changes?

**Comment by pitrou** [comment]
Ping @westonpace

**Comment by westonpace** [comment]
Thanks for the ping.  I haven't had much time for cookbook work recently.  I'll take a look at this one on Friday and either fix it up or close it.

**Comment by westonpace** [comment]
I updated the instructions and ended up changing things a bit further to the dataset new recipes that need to share state between recipes.

**Comment by westonpace** [comment]
Ping @pitrou :)

**Review by pitrou — APPROVED** [review]

**Comment by westonpace** [comment]
I came back to this and realized that @lidavidm 's flight test offers a much better solution.  We can simply move the test body into it's own method that returns a status.  This avoids the complexity of "recipe collections" and, since these tests should be quite small, there is little downside.  So I moved the tests to this approach instead.

**Comment by lidavidm** [comment]
It was @pitrou's suggestion :sweat_smile:

**Pull request merged**
