### PR TITLE
Added License Headers to R module

### PR DESCRIPTION
**Pull request by mystic-lama**
Added License Headers to R module

Adding to index.rmd causes build failure, hence excluded from this PR

### CODE REVIEW

**Comment by mystic-lama** [comment]
@thisisnic This new PR has only relevant changes. Previous one had too much noise.

Not sure why test cases are failing for arrow lob issue. Any pointers?

**Comment by thisisnic** [comment]
Thanks for the updates to this! Looking good now, so happy to merge once the CI passes.

Looks like the previous CI failure was due to the download of the arrow R package failing, so could just be a transient error: https://github.com/apache/arrow-cookbook/runs/7920496703?check_suite_focus=true#step:6:2083

I've re-run the CI job just to check.

**Review by thisisnic — APPROVED** [review]

**Comment by mystic-lama** [comment]
@thisisnic Just curious - how to re-run the CI job? I assume I won't have the privileges

**Comment by thisisnic** [comment]
> @thisisnic Just curious - how to re-run the CI job? I assume I won't have the privileges

That's correct, you don't, but you could send an empty commit or commit then revert a whitespace change or something similar.

**Comment by mystic-lama** [comment]
@lidavidm could you please merge it when you get time

**Comment by lidavidm** [comment]
@mystic-lama note Nic is a committer and can merge things when ready - please try not to ping specific people too much

**Comment by mystic-lama** [comment]
@lidavidm My apologies. Pointed well taken and noted. Shall be careful in future

**Pull request merged**
