### PR TITLE
MINOR: [Release] Update versions for 16.0.0

### PR DESCRIPTION
**Pull request by amoeba**

### CODE REVIEW

**Comment by amoeba** [comment]
Hrm. The C++ cookbook fails in a confusing way,

```
2024-05-23T17:44:42.8285141Z PackagesNotFoundError: The following packages are not available from current channels:
2024-05-23T17:44:42.8285898Z 
2024-05-23T17:44:42.8297664Z   - arrow-nightlies::pyarrow
2024-05-23T17:44:42.8298345Z   - arrow-nightlies::libarrow
```

@raulcd does that make any sense to you?

**Comment by raulcd** [comment]
> @raulcd does that make any sense to you?

Yes, it does. The conda nightly jobs haven't been updated in a really long time on the Arrow repository and have been failing at the moment for the last 73 days. We do clean up "old" conda packages on nightlies and we are supposed to keep some versions https://github.com/apache/arrow/blob/main/dev/tasks/conda-recipes/clean.py#L11 but those might have been deleted as I can't seem to find any on the arrow-nightlies here: https://anaconda.org/arrow-nightlies/repo/files?label=main&type=conda
We should fix the nightlies for conda on the arrow repo.

**Comment by amoeba** [comment]
Thanks @raulcd. So it would seem fine to merge this PR for now and work on fixing the nightlies. For the nightlies, I searched around to understand how that process works (i.e., what's broken) and didn't find much to go off of. I'd be happy to take a look if you could drop some pointers.

**Comment by amoeba** [comment]
Oh, is it just the failures I see on http://crossbow.voltrondata.com/ which are related to the [azure.linux.yml](https://github.com/apache/arrow/blob/main/dev/tasks/conda-recipes/azure.linux.yml) workflow? I see the error about deprecation here which looksl ike a good place to start: https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=64188&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cf5ca333-5432-59fc-78af-35cb2d46743b.

**Comment by amoeba** [comment]
Closing in favor or https://github.com/apache/arrow-cookbook/pull/357.

**Pull request closed without merging**
