### PR TITLE
Closes #27, use pyarrow csv writer

### LINKED ISSUE #27: [Python] Update CSV writing example to use the pyarrow csv writer
It still mentions the fallback to pandas' `to_csv`, but nowadays pyarrow has its own csv writer.

### PR DESCRIPTION
**Pull request by Nlte**

### CODE REVIEW

**Comment by westonpace** [comment]
Unfortunately, it seems we have duplicated some effort here.  #50 is a bit more comprehensive so I will merge that PR.  I'm going to start some new discussions on how we can avoid such things in the future.

**Comment by Nlte** [comment]
Ah right no worries, usually having the little PR icon next to the issue in the issue list allows you to see easily if there's work being done on said issue.
I wanted to put that myself but I don't know how to set that up in github.

**Comment by pitrou** [comment]
Should this PR be closed now?

**Comment by Nlte** [comment]
As far as I'm concerned it can, I'll go ahead.

**Pull request closed without merging**
